//currency 
const countryList = {
  AED: { flag: "AE", country: "United Arab Emirates" },
  AFN: { flag: "AF", country: "Afghanistan" },
  XCD: { flag: "AG", country: "Antigua and Barbuda" },
  ALL: { flag: "AL", country: "Albania" },
  AMD: { flag: "AM", country: "Armenia" },
  ANG: { flag: "AN", country: "Netherlands Antilles" },
  AOA: { flag: "AO", country: "Angola" },
  AQD: { flag: "AQ", country: "Antarctica" },
  ARS: { flag: "AR", country: "Argentina" },
  AUD: { flag: "AU", country: "Australia" },
  AZN: { flag: "AZ", country: "Azerbaijan" },
  BAM: { flag: "BA", country: "Bosnia and Herzegovina" },
  BBD: { flag: "BB", country: "Barbados" },
  BDT: { flag: "BD", country: "Bangladesh" },
  XOF: { flag: "BE", country: "Benin" },
  BGN: { flag: "BG", country: "Bulgaria" },
  BHD: { flag: "BH", country: "Bahrain" },
  BIF: { flag: "BI", country: "Burundi" },
  BMD: { flag: "BM", country: "Bermuda" },
  BND: { flag: "BN", country: "Brunei" },
  BOB: { flag: "BO", country: "Bolivia" },
  BRL: { flag: "BR", country: "Brazil" },
  BSD: { flag: "BS", country: "Bahamas" },
  NOK: { flag: "BV", country: "Bouvet Island" },
  BWP: { flag: "BW", country: "Botswana" },
  BYR: { flag: "BY", country: "Belarus" },
  BZD: { flag: "BZ", country: "Belize" },
  CAD: { flag: "CA", country: "Canada" },
  CDF: { flag: "CD", country: "Democratic Republic of the Congo" },
  XAF: { flag: "CF", country: "Central African Republic" },
  CHF: { flag: "CH", country: "Switzerland" },
  CLP: { flag: "CL", country: "Chile" },
  CNY: { flag: "CN", country: "China" },
  COP: { flag: "CO", country: "Colombia" },
  CRC: { flag: "CR", country: "Costa Rica" },
  CUP: { flag: "CU", country: "Cuba" },
  CVE: { flag: "CV", country: "Cape Verde" },
  CYP: { flag: "CY", country: "Cyprus" },
  CZK: { flag: "CZ", country: "Czech Republic" },
  DJF: { flag: "DJ", country: "Djibouti" },
  DKK: { flag: "DK", country: "Denmark" },
  DOP: { flag: "DO", country: "Dominican Republic" },
  DZD: { flag: "DZ", country: "Algeria" },
  ECS: { flag: "EC", country: "Ecuador" },
  EEK: { flag: "EE", country: "Estonia" },
  EGP: { flag: "EG", country: "Egypt" },
  ETB: { flag: "ET", country: "Ethiopia" },
  EUR: { flag: "FR", country: "Eurozone" },
  FJD: { flag: "FJ", country: "Fiji" },
  FKP: { flag: "FK", country: "Falkland Islands" },
  GBP: { flag: "GB", country: "United Kingdom" },
  GEL: { flag: "GE", country: "Georgia" },
  GGP: { flag: "GG", country: "Guernsey" },
  GHS: { flag: "GH", country: "Ghana" },
  GIP: { flag: "GI", country: "Gibraltar" },
  GMD: { flag: "GM", country: "Gambia" },
  GNF: { flag: "GN", country: "Guinea" },
  GTQ: { flag: "GT", country: "Guatemala" },
  GYD: { flag: "GY", country: "Guyana" },
  HKD: { flag: "HK", country: "Hong Kong" },
  HNL: { flag: "HN", country: "Honduras" },
  HRK: { flag: "HR", country: "Croatia" },
  HTG: { flag: "HT", country: "Haiti" },
  HUF: { flag: "HU", country: "Hungary" },
  IDR: { flag: "ID", country: "Indonesia" },
  ILS: { flag: "IL", country: "Israel" },
  INR: { flag: "IN", country: "India" },
  IQD: { flag: "IQ", country: "Iraq" },
  IRR: { flag: "IR", country: "Iran" },
  ISK: { flag: "IS", country: "Iceland" },
  JMD: { flag: "JM", country: "Jamaica" },
  JOD: { flag: "JO", country: "Jordan" },
  JPY: { flag: "JP", country: "Japan" },
  KES: { flag: "KE", country: "Kenya" },
  KGS: { flag: "KG", country: "Kyrgyzstan" },
  KHR: { flag: "KH", country: "Cambodia" },
  KMF: { flag: "KM", country: "Comoros" },
  KPW: { flag: "KP", country: "North Korea" },
  KRW: { flag: "KR", country: "South Korea" },
  KWD: { flag: "KW", country: "Kuwait" },
  KYD: { flag: "KY", country: "Cayman Islands" },
  KZT: { flag: "KZ", country: "Kazakhstan" },
  LAK: { flag: "LA", country: "Laos" },
  LBP: { flag: "LB", country: "Lebanon" },
  LKR: { flag: "LK", country: "Sri Lanka" },
  LRD: { flag: "LR", country: "Liberia" },
  LSL: { flag: "LS", country: "Lesotho" },
  LTL: { flag: "LT", country: "Lithuania" },
  LVL: { flag: "LV", country: "Latvia" },
  LYD: { flag: "LY", country: "Libya" },
  MAD: { flag: "MA", country: "Morocco" },
  MDL: { flag: "MD", country: "Moldova" },
  MGA: { flag: "MG", country: "Madagascar" },
  MKD: { flag: "MK", country: "North Macedonia" },
  MMK: { flag: "MM", country: "Myanmar" },
  MNT: { flag: "MN", country: "Mongolia" },
  MOP: { flag: "MO", country: "Macau" },
  MRO: { flag: "MR", country: "Mauritania" },
  MTL: { flag: "MT", country: "Malta" },
  MUR: { flag: "MU", country: "Mauritius" },
  MVR: { flag: "MV", country: "Maldives" },
  MWK: { flag: "MW", country: "Malawi" },
  MXN: { flag: "MX", country: "Mexico" },
  MYR: { flag: "MY", country: "Malaysia" },
  MZN: { flag: "MZ", country: "Mozambique" },
  NAD: { flag: "NA", country: "Namibia" },
  XPF: { flag: "NC", country: "New Caledonia" },
  NGN: { flag: "NG", country: "Nigeria" },
  NIO: { flag: "NI", country: "Nicaragua" },
  NPR: { flag: "NP", country: "Nepal" },
  NZD: { flag: "NZ", country: "New Zealand" },
  OMR: { flag: "OM", country: "Oman" },
  PAB: { flag: "PA", country: "Panama" },
  PEN: { flag: "PE", country: "Peru" },
  PGK: { flag: "PG", country: "Papua New Guinea" },
  PHP: { flag: "PH", country: "Philippines" },
  PKR: { flag: "PK", country: "Pakistan" },
  PLN: { flag: "PL", country: "Poland" },
  PYG: { flag: "PY", country: "Paraguay" },
  QAR: { flag: "QA", country: "Qatar" },
  RON: { flag: "RO", country: "Romania" },
  RSD: { flag: "RS", country: "Serbia" },
  RUB: { flag: "RU", country: "Russia" },
  RWF: { flag: "RW", country: "Rwanda" },
  SAR: { flag: "SA", country: "Saudi Arabia" },
  SBD: { flag: "SB", country: "Solomon Islands" },
  SCR: { flag: "SC", country: "Seychelles" },
  SDG: { flag: "SD", country: "Sudan" },
  SEK: { flag: "SE", country: "Sweden" },
  SGD: { flag: "SG", country: "Singapore" },
  SKK: { flag: "SK", country: "Slovakia" },
  SLL: { flag: "SL", country: "Sierra Leone" },
  SOS: { flag: "SO", country: "Somalia" },
  SRD: { flag: "SR", country: "Suriname" },
  STD: { flag: "ST", country: "São Tomé and Príncipe" },
  SVC: { flag: "SV", country: "El Salvador" },
  SYP: { flag: "SY", country: "Syria" },
  SZL: { flag: "SZ", country: "Eswatini" },
  THB: { flag: "TH", country: "Thailand" },
  TJS: { flag: "TJ", country: "Tajikistan" },
  TMT: { flag: "TM", country: "Turkmenistan" },
  TND: { flag: "TN", country: "Tunisia" },
  TOP: { flag: "TO", country: "Tonga" },
  TRY: { flag: "TR", country: "Turkey" },
  TTD: { flag: "TT", country: "Trinidad and Tobago" },
  TWD: { flag: "TW", country: "Taiwan" },
  TZS: { flag: "TZ", country: "Tanzania" },
  UAH: { flag: "UA", country: "Ukraine" },
  UGX: { flag: "UG", country: "Uganda" },
  USD: { flag: "US", country: "United States" },
  UYU: { flag: "UY", country: "Uruguay" },
  UZS: { flag: "UZ", country: "Uzbekistan" },
  VEF: { flag: "VE", country: "Venezuela" },
  VND: { flag: "VN", country: "Vietnam" },
  VUV: { flag: "VU", country: "Vanuatu" },
  YER: { flag: "YE", country: "Yemen" },
  ZAR: { flag: "ZA", country: "South Africa" },
  ZMK: { flag: "ZM", country: "Zambia" },
  ZWD: { flag: "ZW", country: "Zimbabwe" }
};
